# Function

In [1]:
#No parameter no return
def greet():
    print("Hello, World!")
greet()

Hello, World!

In [4]:
#With parameter no return
def greet(name = "None"):
    print(f"Hello, {name}!")
greet("Alice")
greet()

Hello, Alice!
Hello, None!

In [11]:
def adder(x, y):
    """ArithmeticError: This function performs addition of two numbers."""
    return x + y

print(adder(5, 3))

def add(x, y):
    sum = x + y
    print(sum)
add(5, 3)


try:
    m = add(10,20) * 5
    print(m) 
except TypeError as e:
    print(f"Error: {e}.")

#but
m = adder(10,20) * 5
print(m)

8
8
30
Error: unsupported operand type(s) for *: 'NoneType' and 'int'.
150

In [13]:
help(adder)
help(print)

Help on function adder in module __main__:

adder(x, y)
    ArithmeticError: This function performs addition of two numbers.

Help on built-in function print in module builtins:

print(*args, sep=' ', end='\n', file=None, flush=False)
    Prints the values to a stream, or to sys.stdout by default.

    sep
      string inserted between values, default a space.
    end
      string appended after the last value, default a newline.
    file
      a file-like object (stream); defaults to the current sys.stdout.
    flush
      whether to forcibly flush the stream.

## Arguments and Parameters

In [20]:
# Positional arguments
def add(a, b, c):
    print(f"{a}, {b}, {c}")

add(1, 4, 3)

#but
add(b=1, c=4, a=3)

1, 4, 3
3, 1, 4

In [19]:
# Many args
def add(*args):
    print(args)
    for i in args: # Two ways!
        print(i)

add(1, 2, 3, 4, 5)

(1, 2, 3, 4, 5)
1
2
3
4
5

In [30]:
def add(**kwargs):
    print(kwargs)

    for key, value in kwargs.items():
        print(f"{key} = {value}")

add(a=1, b=2, d=4, n_estimator=50)

{'a': 1, 'b': 2, 'd': 4, 'n_estimator': 50}
a = 1
b = 2
d = 4
n_estimator = 50

In [41]:
# Some interesting examples
def adder(a,b):
    return a, b

print(type(adder(1,2)))

def adder(a,b):
    return a + b, a - b
print(type(adder(1,2)), adder(1,2))

def adder(a,b):
    return a, b

#unzip

x,y = adder(10.5 ,20)
print(x, y)

<class 'tuple'>
<class 'tuple'> (3, -1)
10.5 20

## Iterators and Generators

In [53]:
some_list = [1, 2, 3, 4, 5]
print(some_list[1])

s = {10, 20, 30, 40, 50}
#print(s[1]) 

s_iter = iter(s)
print(s_iter)
print(type(s_iter))
print(next(s_iter))
print(next(s_iter))
print(next(s_iter))
print(next(s_iter))
print(next(s_iter))
# Random : This happens cuz set is not ordered.
for i in s:
    print(i) #This seems easy.

2
<set_iterator object at 0x109e35300>
<class 'set_iterator'>
50
20
40
10
30
50
20
40
10
30

In [60]:
list = [x for x in range (500)]

def data_loader(batch_size, list):
    for i in range(0, len(list), batch_size):
        yield list[i:i+batch_size]

x = data_loader(10, list)
print(type(x))
print(x)
print(next(x))
print(next(x))

<class 'generator'>
<generator object data_loader at 0x109ae6a70>
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

## Lambda, Map, Apply Funcunctions

In [67]:
# Lambda a : expression
import pandas as pd

df = pd.DataFrame({'Temperature (C)': [30, 32, 28.0, 25, 27]})
df['Temperature (F)'] = df['Temperature (C)'].apply(lambda x: (x * 9/5) + 32)
df

   Temperature (C)  Temperature (F)
0             30.0             86.0
1             32.0             89.6
2             28.0             82.4
3             25.0             77.0
4             27.0             80.6

In [71]:
df = pd.DataFrame({'A': [1, 2, 3, 4, 5], 'B': [10, 20, 30, 40, 50]})
df

df['B'] = df['B'].map(lambda x: x ** .5)
df

   A         B
0  1  3.162278
1  2  4.472136
2  3  5.477226
3  4  6.324555
4  5  7.071068

## 6.5